=== KeilaCruz/DTD_XML_CatalogoMusical/catalagoMusical.dtd
<!ELEMENT catalagomusical (album+)>
<!ELEMENT album (titulo, artista, genero, lanzamiento, cancion+)>
<!ELEMENT titulo(#PCDATA)>
<!ELEMENT artista(#PCDATA)>
<!ELEMENT genero(#PCDATA)>
<!ELEMENT lanzamiento(#PCDATA)>
<!ELEMENT cancion(titulo, artista, duracion)>
<!ELEMENT duracion(#PCDATA)>

<!ATTLIST album id CDATA #REQUIRED>
<!ATTLIST titulo nombre CDATA #REQUIRED>
<!ATTLIST artista pseudonimo CDATA #REQUIRED>
<!ATTLIST genero tipo(Rock|Pop|Jazz|HipHop|Blues|Otro) #REQUIRED>
<!ATTLIST lanzamiento fecha DATE #REQUIRED> 
<!ATTLIST cancion id CDATA #REQUIRED> 
<!ATTLIST duracion time CDATA #REQUIRED>

=== KeilaCruz/DTD_XML_CatalogoMusical/catalogoMusical.xml
<?xml version="1.0"?>
<!DOCTYPE catalogomusical SYSTEM "catalagoMusical.dtd">
<catalagomusical>
<album id="1">
<titulo nombre="navidades">Navidades</titulo>
<artista pseudonimo="luismi">Luis Miguel</artista>
<genero tipo="Otro">Villancico</genero>
<lanzamiento fecha="2006-11-14">14 de Noviembre del 2006</lanzamiento>
<cancion id="1navidades">
    <titulo>Santa Claus lleg√≥ a la ciudad</titulo>
    <artista>Luis Miguel</artista>
    <duracion time="01:56">Un minuto cincuenta y seis segundos (1:56 minutos)</duracion>
</cancion>
<cancion id="2navidades">
    <titulo>Blanca navidad</titulo>
    <artista>Luis Miguel</artista>
    <duracion time="03:30">Tres minutos y treinta segundos (3:30 minutos)</duracion>
</cancion>
<duracion time="31:30">Treinta y un minutos con treinta segundos(31:30 minutos)</duracion>
</album>
</catalagomusical>
